language: ruby
rvm:
  - "2.3.3"
  # - jruby-19mode # JRuby in 1.9 mode
  # - rbx-19mode
branches:
  only:
  - v2

# uncomment this line if your project needs to run something other than `rake`:
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec --no-drb

notifications:
  slack:
    secure: "bPPGTQMwfLuZML83JqNezuBJwAYwXNhmKV1mz7mOtktGkwX6m8WugRXB/e4Rouc+J/JL5yc0iVtVIsnBe/KgTrubtOP5dsK8hpI4GeZqzMt7psnkBDG2/xKHfPvNeAnztrPoCv9sLQNDMoep8G+8hEtn8CQ7aosa8iJLw5rGFhA="

